
redshift = {'dbname': 'cdeprddb',
            'host': 'itx-ags-prd-rs-cl-01.cku868xglwj7.us-east-1.redshift.amazonaws.com',
            'port': '5439',
            'user': 'eureka_prd_read',
            'password': '=1j-uL9xpOfF'

}

lens_poc = {
    'q1_retail': 'select thrc_class_cd, caln_dt, sls.jnj_id, cot_seg_val, catg_cd,  sls.prod_lst_id, src_cd, suplr_nm, estmt_flg, new_rx_cnt, new_rx_uns, new_rx_equiv_uns, tot_rx_cnt, tot_rx_uns, tot_rx_equiv_uns, cust_nm, npi_id, prim_spclt_nm, secry_spclt_nm, addr_ln1, addr_ln2, city_nm, zip_cd, cntry, stt_cd, prod_nm, prod_disply_nm, is_jnj_flg, sls.pln_sid, payer.pln_desc, payer.pln_mdel_typ_cd, payer.payr_id, payer.payr_descn, payer.pbm_id, payer.pbm_desc, terr.co_cd, terr.co_nm, terr.fran_cd, terr.reg_rdt_no, terr.terr_rdt_no, terr.distrc_rdt_no, terr.reg_nm, terr.distrc_nm,terr.terr_nm from cdp.fct_pln_ret_sls_curr_wkly sls,cdp.Dmn_cust cust, cdp.dmn_addr addr, cdp.dmn_prod prod, cdp.dmn_payr_pln payer, cdp.dmn_model_groups mdl, cdp.dmn_terr terr where sls.cust_sid = cust.cust_sid and sls.addr_sid = addr.addr_sid and sls.prod_sid = prod.prod_sid and sls.pln_sid = payer.pln_sid and sls.thrc_class_cd = \'PRC\' and payer.pln_mdel_typ_cd= mdl.model and sls.terr_sid = terr.terr_sid limit 300000',
    'q2_retail_aligned_sales': 'select thrc_class_cd, caln_dt, sls.jnj_id, cot_seg_val, catg_cd,  sls.prod_lst_id, src_cd, suplr_nm, estmt_flg, new_rx_cnt, new_rx_uns, new_rx_equiv_uns, tot_rx_cnt, tot_rx_uns, tot_rx_equiv_uns, cust_nm, npi_id, prim_spclt_nm, secry_spclt_nm, addr_ln1, addr_ln2, city_nm, zip_cd, cntry, stt_cd, prod_nm, prod_disply_nm, is_jnj_flg, sls.pln_sid, payer.pln_desc, payer.pln_mdel_typ_cd, payer.payr_id, payer.payr_descn, payer.pbm_id, payer.pbm_desc, terr.co_cd, terr.co_nm, terr.fran_cd, terr.reg_rdt_no, terr.terr_rdt_no, terr.distrc_rdt_no, terr.reg_nm, terr.distrc_nm,terr.terr_nm from cdp.fct_pln_ret_sls_curr_wkly sls,cdp.Dmn_cust cust, cdp.dmn_addr addr, cdp.dmn_prod prod, cdp.dmn_payr_pln payer, cdp.dmn_model_groups mdl, cdp.dmn_terr terr where sls.cust_sid = cust.cust_sid and sls.addr_sid = addr.addr_sid and sls.prod_sid = prod.prod_sid and sls.pln_sid = payer.pln_sid and sls.thrc_class_cd = \'PRC\' and payer.pln_mdel_typ_cd= mdl.model and sls.terr_sid = terr.terr_sid limit 300000;',
    'q3_non-retail-unaligned-sales': 'select thrc_class_cd, caln_dt, sls.jnj_id, cot_seg_val, catg_cd,  sls.prod_lst_id, src_cd, suplr_nm, estmt_flg, uns, equiv_uns, cust_nm, npi_id, prim_spclt_nm, secry_spclt_nm, addr_ln1, addr_ln2, city_nm, zip_cd, cntry, stt_cd, prod_nm, prod_disply_nm, is_jnj_flg from cdp.fct_nonret_sls_trans_wkly sls,cdp.Dmn_cust cust, cdp.dmn_addr addr, cdp.dmn_prod prod where sls.cust_sid = cust.cust_sid and sls.addr_sid = addr.addr_sid and sls.prod_sid = prod.prod_sid and sls.thrc_class_cd = \'PRC\' limit 300000;',
    'q4_non_retail_aligned_sales': 'select thrc_class_cd, caln_dt, sls.jnj_id, cot_seg_val, catg_cd,  sls.prod_lst_id, src_cd, suplr_nm, estmt_flg, uns, equiv_uns, cust_nm, npi_id, prim_spclt_nm, secry_spclt_nm, addr_ln1, addr_ln2, city_nm, zip_cd, cntry, stt_cd, prod_nm, prod_disply_nm, is_jnj_flg, terr.co_cd, terr.co_nm, terr.fran_cd, terr.reg_rdt_no, terr.terr_rdt_no, terr.distrc_rdt_no, terr.reg_nm, terr.distrc_nm,terr.terr_nm from cdp.fct_nonret_sls_curr_wkly sls,cdp.Dmn_cust cust, cdp.dmn_addr addr, cdp.dmn_prod prod, cdp.dmn_terr terr where sls.cust_sid = cust.cust_sid and sls.addr_sid = addr.addr_sid and sls.prod_sid = prod.prod_sid and sls.thrc_class_cd = \'PRC\' and sls.terr_sid = terr.terr_sid limit 300000;',
    'threadCount': 1
}
